# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=256, verbose_name='Serial No')),
                ('access_token', models.CharField(max_length=256, verbose_name='Token')),
            ],
        ),
    ]
